blockchain:
  difficulty: 2
  server_address: http://localhost:5002

metronome:
  block_generation_interval: 6
  netspace: 1000
  server_address: http://localhost:5003
  validators:
    - http://localhost:5007
    

monitor:
  blockchain_server: http://localhost:5002
  metronome_server: http://localhost:5003
  server_address: http://localhost:5008
  validator_server: http://localhost:5007

pool:
  blockchain_address: http://localhost:5002
  metronome_server: http://localhost:5003
  server_address: http://localhost:8003
  validator_server: http://localhost:5007


validator:
  blockchain_server: http://localhost:5002
  fingerprint: e78db409b05a7ce6ce2b3d4d68781eb83ec7038a56ff16440f617926f3df4635
  metronome_server: http://localhost:5003
  proof_config:
    enable: true
    algorithm: "pos"
    threads: 4  # Set the desired number of threads for Proof of Space
    storage: 1024  # Set the desired storage size in MB
    buckets: 256   # Set the number of buckets
    bucket_size: 4096  # Set the bucket size in bytes
    write_size: 512    # Set the write size in bytes
    ram: 1024  # Set the RAM size in MB
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrxb4w/i+J3RTjCFr0kjYsUcuiByltZ18e93NNV3jTAvlShMqDmNJOsEgxLv2825nDtY4FkGhbWWoXM6H8BSDRPGp7uRInpxufq4q8DsDMY+w+bagt+AD05u9FAGjG+dGc55MLK+0bN/zHcmK7aYm74YhpsePb8FQeSG+rsPWjH9IPEhAYXahgYg7x+Xa1gVDXZYChuSJBidS3bidrQ/agYhx3wH1gSg/A3kzeWclr4P5Kxl1PWvqgZA97J926aYVmfRhKaW0GUt12t6NywRHux64nIE+EP3ye8eFOQQE75rgXS9Z5Ui1Fxpyqxeg6rXLpNSCaWaLKXNxuyceKdtM1

wallet:
  private_key_path: C:\Users\Admin\Desktop\Project\dsc-key.yaml
  public_key: a4608433b5edf55040f4fd89b3ae2dabf6bedc4282251209a7bf3c69b6f2e1b6
